D0C-49 Instructions for installing repo
welkincloud-io/sample-apps pull request #2
Opened 2022-01-27 13:49 UTC by sarangamborkar

2022-01-27 19:17 UTC, reykatz requested changes
This looks good, thanks for adding the instructions! I've left a couple comments with the commands that worked on my setup with python3.

2022-01-27 19:17 UTC, reykatz commented on README.md
> +$ virtualenv venv
I had to specify python3 when setting up my virtualenv:
`virtualenv -p python3 venv`

2022-01-27 19:17 UTC, reykatz commented on README.md
> +
Can we add a header saying this is Mac installation instructions?
`#### How to Install on Mac OS` or similar?

2022-01-27 19:17 UTC, reykatz commented on README.md
> +$ python -m pip install -r requirements.txt
Same here, I had to use pip3 instead of pip:
`pip3 install -r requirements.txt`
(The `python -m` was not needed)

2022-01-28 07:10 UTC, sarangamborkar commented
I added Admin portal security setting instruction in same request. can you please take look and suggest me if any changes required

2022-01-31 22:01 UTC, reykatz approved these changes
Looks good to me

2022-02-01 07:54 UTC, merged